version: '3.8'
services:

  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - '6379:6379'
    # Persistance AOF : sauvegarde chaque seconde
    # En cas de redémarrage, les sessions et paniers sont restaurés
    command: redis-server --appendonly yes --appendfsync everysec
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  app1:
    build: ./app
    container_name: app1
    environment:
      PORT: 3001
      INSTANCE: 'Instance-1'
      MONGO_URI: mongodb://mongodb:27017/boutique
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    volumes:
      - uploads_data:/app/uploads
    depends_on: [mongodb, redis, rabbitmq]

  app2:
    build: ./app
    container_name: app2
    environment:
      PORT: 3002
      INSTANCE: 'Instance-2'
      MONGO_URI: mongodb://mongodb:27017/boutique
      REDIS_HOST: redis
      REDIS_PORT: 6379
      RABBITMQ_URL: amqp://admin:admin@rabbitmq
    volumes:
      - uploads_data:/app/uploads
    depends_on: [mongodb, redis, rabbitmq]

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on: [app1, app2]

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - uploads_data:/app/uploads
    depends_on: [frontend, app1, app2]

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
  uploads_data:
